services:
  app:
    build: .
    container_name: newsfeed_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # Override default threshold if needed
      - RELEVANCE_THRESHOLD=0.1
